global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  # HTTPS availability for your frontend (through NGINX on host)
  - job_name: blackbox_https_frontend
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://host.docker.internal:443/   # your published NGINX 443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # Host VM metrics (CPU, memory, disk)
  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: nginx
    static_configs:
      - targets: ["nginx-exporter:9113"]