name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t backend:latest ./backend

      - name: Run Unit Tests (Optional)
        run: |
          echo "Run your backend tests here"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop backend || true
            docker rm backend || true
            docker pull myrepo/backend:latest
            docker run -d --name backend -p 4000:4000 myrepo/backend:latest

