name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - week4
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "EC2_HOST is: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER is: ${{ secrets.EC2_USER }}"
          echo "EC2_KEY is: ${{ secrets.EC2_KEY }}"
        shell: bash

#      - name: Build Docker Image
#        run: |
#          docker build -t backend:latest ./backend

      - name: Run Unit Tests (Optional)
        run: |
          echo "Run your backend tests here"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker-compose stop backend || true
            docker-compose up backend -d --build

