name: Deploy Backend

on:
  push:
    branches:
      - '**'         # All branches
    paths:
      - '**'         # All files and folders
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g., aws)'
        required: true
        default: 'aws'
env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'aws' }}

    steps:
      - name: Deploy backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: BRANCH_NAME  # 🚀 inject branch into SSH session
          script: |
            set -e

            echo "Deploying branch: $BRANCH_NAME"

            REPO="https://github.com/nandhab/devops-3tier-docker-cicd-aws.git"
            DIR="devops-3tier-docker-cicd-aws"

            if [ ! -d "$DIR" ]; then
              git clone -b "$BRANCH_NAME" "$REPO"
            else
              cd "$DIR"
              git fetch origin
              git reset --hard origin/"$BRANCH_NAME"
              cd ..
            fi

            cd "$DIR"

            echo "Stopping any existing backend container..."
            docker stop backend || true
            docker rm backend || true

            echo "Building and running backend container..."
            docker-compose up -d
